# Generated by Django 5.0 on 2023-12-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='images',
            new_name='image',
        ),
    ]
